# Netlify configuration for Terminal Screenshot Generator
# This file configures redirects for SPA routing

[build]
  publish = "dist"
  command = "npm run build"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.environment]
  NODE_VERSION = "18"
